alter table UNIVERCITYPRACTICE_AUDITORIUM alter column NUMBER_CABINET rename to NUMBER_CABINET__U23098 ^
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column NUMBER_CABINET__U23098 set null ;
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column CAPACITY rename to CAPACITY__U77106 ^
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column CAPACITY__U77106 set null ;
alter table UNIVERCITYPRACTICE_AUDITORIUM add column NUMBER_OF_GROUP integer ;
alter table UNIVERCITYPRACTICE_AUDITORIUM add column NUMBER_CABINET integer ^
update UNIVERCITYPRACTICE_AUDITORIUM set NUMBER_CABINET = 0 where NUMBER_CABINET is null ;
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column NUMBER_CABINET set not null ;
