alter table UNIVERCITYPRACTICE_AUDITORIUM alter column LECTURE_ID rename to LECTURE_ID__U12118 ^
alter table UNIVERCITYPRACTICE_AUDITORIUM drop constraint FK_UNIVERCITYPRACTICE_AUDITORIUM_ON_LECTURE ;
drop index IDX_UNIVERCITYPRACTICE_AUDITORIUM_ON_LECTURE ;
alter table UNIVERCITYPRACTICE_AUDITORIUM add column LECTURE_NUMBERCABINET varchar(36) ;
