alter table UNIVERCITYPRACTICE_EMPLOYMENT add column NAME_EMPLOYAMENT longvarchar ^
update UNIVERCITYPRACTICE_EMPLOYMENT set NAME_EMPLOYAMENT = '' where NAME_EMPLOYAMENT is null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column NAME_EMPLOYAMENT set not null ;
