alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column NAME_EMPLOYAMENT rename to NAME_EMPLOYAMENT__U15612 ^
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column NAME_EMPLOYAMENT__U15612 set null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column TIME_ rename to TIME___U92639 ^
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column TIME___U92639 set null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT add column NAME_EMPLOYMENT longvarchar ^
update UNIVERCITYPRACTICE_EMPLOYMENT set NAME_EMPLOYMENT = '' where NAME_EMPLOYMENT is null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column NAME_EMPLOYMENT set not null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT add column START_TIME time ^
update UNIVERCITYPRACTICE_EMPLOYMENT set START_TIME = current_time where START_TIME is null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column START_TIME set not null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT add column DURATION integer ^
update UNIVERCITYPRACTICE_EMPLOYMENT set DURATION = 0 where DURATION is null ;
alter table UNIVERCITYPRACTICE_EMPLOYMENT alter column DURATION set not null ;
