alter table UNIVERCITYPRACTICE_AUDITORIUM alter column LECTURE_ID rename to LECTURE_ID__U30455 ^
alter table UNIVERCITYPRACTICE_AUDITORIUM drop constraint FK_UNIVERCITYPRACTICE_AUDITORIUM_ON_LECTURE ;
drop index IDX_UNIVERCITYPRACTICE_AUDITORIUM_ON_LECTURE ;
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column LABORATORY_NUMBERCABINET rename to LABORATORY_NUMBERCABINET__U70416 ^
alter table UNIVERCITYPRACTICE_AUDITORIUM drop constraint FK_UNIVERCITYPRACTICE_AUDITORIUM_ON_LABORATORY_NUMBERCABINET ;
drop index IDX_UNIVERCITYPRACTICE_AUDITORIUM_ON_LABORATORY_NUMBERCABINET ;
alter table UNIVERCITYPRACTICE_AUDITORIUM add column NUMBER_CABINET varchar(255) ^
update UNIVERCITYPRACTICE_AUDITORIUM set NUMBER_CABINET = '' where NUMBER_CABINET is null ;
alter table UNIVERCITYPRACTICE_AUDITORIUM alter column NUMBER_CABINET set not null ;
